version: "3"
services:
  plaid-proxy:
    depends_on:
      - plaid-web
      - plaid-server
    build: proxy
    ports:
      - "443:443"
    environment:
      - ENABLE_IPV6=true
      - NGINX_LISTEN_PORT=80
      - NGINX_WEB_PORT=3000
      - NGINX_SERVER_PORT=5000
    networks:
      - mern-app
      - default

  plaid-web:
    build: web
    environment:
      PORT: 3000
    networks:
      - mern-app
    depends_on:
      - plaid-server

  plaid-server:
    build: server
    environment:
      MONGO_IP: mongo
      MONGO_PORT: 27017
      PORT: 5000
    networks:
      - mern-app
      - default
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    expose:
      - 27017
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db

networks:
  default:
  mern-app:
    driver: bridge

volumes:
  mongo-data:
    driver: local
