version: "3"
services:
  plaid-proxy:
    depends_on:
      - plaid-web
      - plaid-server
    build: proxy
    ports:
      - "443:443"
    environment:
      - ENABLE_IPV6=true
    networks:
      - mern-app
      - default
    restart: always

  plaid-web:
    build: web
    command: npm run start
    environment:
      PORT: 3000
      NODE_ENV: development
    networks:
      - mern-app
    depends_on:
      - plaid-server
    volumes:
      - ./web:/usr/src/app
      - ./web/node_modules:/usr/src/app/node_modules
    restart: always

  plaid-server:
    build: server
    command: npm run dev
    # 9229 must be forwarded to attach a debugger to the container
    ports:
      - "9229:9229"
    environment:
      NODE_ENV: development
      PLAID_CLIENT_ID: REPLACEME
      PLAID_SECRET: REPLACEME
      PLAID_ENVIRONMENT: sandbox
      MONGO_USER: user
      MONGO_PASSWORD: pass
    networks:
      - mern-app
      - default
    depends_on:
      - mongo
    volumes:
      # r/o copy of build files
      - ./server:/usr/src/app:ro
      # don't copy node_modules
      - /usr/src/app/node_modules

  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass


