version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    depends_on:
      - plaid-web
      - plaid-server
    ports:
      - "443:443"
    environment:
      - ENABLE_IPV6=true
      - LISTEN_PORT=443
      - WEB_PORT=3000
      - SERVER_PORT=5000
      - PUBLIC_URL=mysite.com
    volumes:
      - ./nginx/conf/:/etc/nginx/templates/
      - ./nginx/cert/:/etc/nginx/ssl/

  plaid-web:
    environment:
      PORT: 3000
    depends_on:
      - plaid-server

  plaid-server:
    build: server
    environment:
      MONGO_IP: mongo
      MONGO_PORT: 27017
      PORT: 5000
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
