version: "3"
services:
  nginx:
    restart: always

  plaid-web:
    build:
      context: web/
      dockerfile: Dockerfile.prod
    environment:
      NODE_ENV: production
    restart: always

  plaid-server:
    environment:
      NODE_ENV: production
      PLAID_CLIENT_ID: REPLACEME
      PLAID_SECRET: REPLACEME
      PLAID_ENVIRONMENT: production
    restart: always

  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    restart: always
