FROM node:15-alpine
WORKDIR /app
COPY package*.json ./
# Don't install dev packages in production
RUN if [ "$NODE_ENV" = "production" ]; \
        then npm ci --only=production; \
        else npm i; \
        fi
COPY . ./
ENV PORT 3000
EXPOSE $PORT
CMD [ "npm", "run", "start" ]
